In [2]:
# Day14-15 Assignment Batch1 AIML
# Venkkatesh V R 

In [3]:
import numpy as np

# 1. Create a 3x3x3 array with random values 

In [4]:
np.random.rand(3,3,3)

array([[[0.95071884, 0.31832898, 0.64202629],
        [0.10176779, 0.18977506, 0.20533649],
        [0.83286686, 0.38344433, 0.81230527]],

       [[0.25668106, 0.78532315, 0.3861018 ],
        [0.62165385, 0.05345327, 0.32337968],
        [0.85597638, 0.98366425, 0.06213738]],

       [[0.49423569, 0.31935086, 0.2823918 ],
        [0.7201519 , 0.26167101, 0.99913598],
        [0.26292457, 0.40065242, 0.8071942 ]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [5]:
arr =np.zeros((5,5))  #creates a 5x5 matrix with zeros

print(arr)

for i in range(len(arr)):
    if i > 0:
        arr[i][i-1] = i
          
print("\nArray after Modification\n")            
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

Array after Modification

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [20]:
diag = np.diag(1+np.arange(4), k = -1)
print (diag)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [6]:
arr =np.zeros((8,8))  #creates a 5x5 matrix with zeros

print(arr)

for i in range(len(arr)):
    for j in range(len(arr)):
        if i in [0,2,4,6]:
            if (j%2 != 0):
                arr[i][j] = 1
        else:
            if (j%2 == 0):
                arr[i][j] = 1
          
print("\nArray after Modification\n")            
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]

Array after Modification

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [21]:
array= np.array([[0,1], [1,0]])
arr2 = np.tile(array,(4,4))
print (arr2)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [7]:
arr = np.random.random((5,5))
print(arr)

narr = (arr - np.mean(arr)) / (np.std(arr))
print("\n After normalize\n")
print(narr)

[[0.48878609 0.42738928 0.30448739 0.13717838 0.75186375]
 [0.74827951 0.40523893 0.9383752  0.31218784 0.52279189]
 [0.79506125 0.31592752 0.91599867 0.25042265 0.5652929 ]
 [0.69218134 0.43930374 0.01585604 0.91364549 0.04944952]
 [0.34921233 0.39204719 0.98278964 0.4060728  0.87079049]]

 After normalize

[[-0.11039047 -0.33016408 -0.77009892 -1.36899174  0.8313121 ]
 [ 0.8184821  -0.40945261  1.49894123 -0.74253469  0.01133538]
 [ 0.98594022 -0.72914827  1.41884309 -0.96362697  0.16347036]
 [ 0.61767527 -0.28751557 -1.80327248  1.41041975 -1.68302256]
 [-0.61000327 -0.45667325  1.65792545 -0.40646774  1.25701766]]


In [24]:
arr = np.random.random((5,5))
print(arr)
arr= (arr - arr.min())/(arr.max() - arr.min())
print (arr)

[[0.41944792 0.23282784 0.23446912 0.45469371 0.69806263]
 [0.74828499 0.89121002 0.53229995 0.35875084 0.01338394]
 [0.44821848 0.2552506  0.96669431 0.43910708 0.03382242]
 [0.73215716 0.03166418 0.51465425 0.03304697 0.25788397]
 [0.90329041 0.98967188 0.12539151 0.13892134 0.61783164]]
[[0.41592646 0.22477375 0.2264549  0.45202829 0.70130815]
 [0.75275032 0.8991467  0.53151943 0.35375516 0.        ]
 [0.4453958  0.24774111 0.97646435 0.43606309 0.02093489]
 [0.73623077 0.01872423 0.51344515 0.02014061 0.25043844]
 [0.9115205  1.         0.11472801 0.12858645 0.61912851]]


# 5.  How to find common values between two arrays?

In [8]:
arr1 = np.random.randint(0,10,5)
arr2 = np.random.randint(0,10,5)
print(np.intersect1d(arr1,arr2))

[0 7]


# 6.How to get the dates of yesterday, today and tomorrow?

In [9]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday)
print(today)
print(tomorrow)

2020-08-01
2020-08-02
2020-08-03


# 7. Consider two random array A and B, check if they are equal

In [10]:
arr1 = np.random.randint(0,10,5)
arr2 = np.random.randint(0,10,5)
print(np.array_equal(arr1,arr2))

False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [11]:
arr = np.random.random(10)
print(arr)
ix = np.where(arr == np.amax(arr))
print(ix)
arr[ix[0]] = 0
print("\n After modify the vactor\n")
print(arr)

[0.08527024 0.64209515 0.75589209 0.92259534 0.51482375 0.75086957
 0.75931552 0.63542639 0.49484118 0.3289116 ]
(array([3], dtype=int64),)

 After modify the vactor

[0.08527024 0.64209515 0.75589209 0.         0.51482375 0.75086957
 0.75931552 0.63542639 0.49484118 0.3289116 ]


In [27]:
arr = np.random.randint(10,size=5)
print(arr)
arr[arr.argmax()] = 0
print(arr)

[0 0 0 9 3]
[0 0 0 0 3]


# 9. How to print all the values of an array?

In [12]:
arr = np.random.randint(0,10,5)
print(arr)

[2 2 7 2 7]


In [31]:
arr = np.ones((5,5))
np.set_printoptions(threshold=np.inf)
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# 10.Subtract the mean of each row of a matrix

In [13]:
arr = np.random.randn(5, 5)
print(arr)
arr = arr - np.mean(arr,axis=1)
print("\n after mean subraction\n")
print(arr)

[[ 0.88774034 -0.36002971  0.04392512 -0.28856    -0.51548572]
 [ 0.30399499 -0.00290849  0.54115824 -0.6704982   0.66321941]
 [-0.1274974  -0.3446087  -0.53005444 -0.65995204 -0.2910739 ]
 [-1.12176955  1.61551783 -1.48927669 -0.56472489 -0.36086702]
 [ 0.10245934  1.13282837 -1.4722305  -0.36958996 -0.55437574]]

 after mean subraction

[[ 0.93422233 -0.5270229   0.43456241  0.09566407 -0.28330402]
 [ 0.35047699 -0.16990168  0.93179553 -0.28627413  0.89540111]
 [-0.0810154  -0.51160189 -0.13941714 -0.27572798 -0.0588922 ]
 [-1.07528756  1.44852464 -1.09863939 -0.18050083 -0.12868532]
 [ 0.14894133  0.96583518 -1.08159321  0.01463411 -0.32219405]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [17]:
arr1= np.random.randint(0,5,10)
print(arr1)
arr2= np.random.randint(0,10,10)
print (arr2)

[2 1 4 0 4 3 1 1 2 4]
[4 4 6 1 1 8 4 1 6 3]


In [19]:
arr3 = np.bincount(arr2, minlength=len(arr1))
print(arr1)
print(arr3)
arr1 += arr3

print (arr1)

[2 4 4 1 7 3 3 1 3 4]
[0 3 0 1 3 0 2 0 1 0]
[ 2  7  4  2 10  3  5  1  4  4]


# 12.How to get the diagonal of a dot product?

In [42]:
arr = np.random.randn(5, 5)
arr1 = np.random.randn(5, 5)
print(arr)
print(arr1)
print("\n Diagonal of the dot product of 2 array\n")
print(np.diag(np.dot(arr,arr1)))

[[ 0.57990654 -0.63911769  0.65621818  0.4526842  -0.83924963]
 [-0.21247543  0.2673217   0.47013861 -0.74283273 -0.76245898]
 [-0.64168134  1.2610568   0.67166619 -0.06231081 -0.6363747 ]
 [ 0.5334161   2.07721372  1.27734955  0.58383425  0.43135008]
 [-0.50424805 -0.79625526  0.44966745  0.04128878 -0.13222434]]
[[ 1.17709701  1.66155087  0.01880006 -2.1806404  -0.65890895]
 [-0.77616917 -0.56891722 -1.51640129  0.64455563  0.39148129]
 [ 1.33612174  1.09391564  1.75792656 -0.04146176  0.08253962]
 [-0.22824325 -1.0089765  -0.83003165  0.48158735  2.12950339]
 [-0.32581777  0.75098695  0.33783814  0.83438235  1.61522406]]

 Diagonal of the dot product of 2 array

[ 2.22557741  0.18607335 -0.90686369  0.76380803 -0.06799745]


# 13.How to find the most frequent value in an array?

In [44]:
arr = np.random.randint(0,10,30)
print(arr)
print("most frequent value is :",np.bincount(arr).argmax())

[0 7 6 9 8 5 5 9 3 6 1 9 9 0 7 9 0 8 1 9 9 7 9 2 8 6 6 2 4 4]
most frequent value is : 9


# 14.How to get the n largest values of an array

In [46]:
arr = np.arange(10)
print(arr)

np.random.shuffle(arr)
n = 4
print (arr[np.argsort(arr)[-n:]])

[0 1 2 3 4 5 6 7 8 9]
[6 7 8 9]


# 15.How to create a record array from a regular array?

In [47]:
arr = np.array([("Honda", "Amaze", 2014),
                 ("Maruti", "Zen", 2018),
             ("Ford", "Ecosport", 2016)])

print(arr)

print("\nRecord array\n")
rarr = np.core.records.fromarrays(arr.T,
                              names='col1, col2, col3',
                              formats = 'S10, S10, i8')
print(rarr)

[['Honda' 'Amaze' '2014']
 ['Maruti' 'Zen' '2018']
 ['Ford' 'Ecosport' '2016']]

Record array

[(b'Honda', b'Amaze', 2014) (b'Maruti', b'Zen', 2018)
 (b'Ford', b'Ecosport', 2016)]


In [48]:
# End of Assignment